Fix non-localized string
StanfordSpezi/SpeziAccount pull request #33
Opened 2023-10-31 03:55 UTC by vishnuravi

# Fix non-localized string

## :gear: Release Notes 
Fixes a string that is not being drawn from the localization files.

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [X] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

2023-10-31 04:02 UTC, vishnuravi commented
@Supereg any idea why we are getting the `discouraged_optional_collection` error here? Those files were not touched and seemed to have passed before?

2023-10-31 04:54 UTC, Supereg commented
> @Supereg any idea why we are getting the `discouraged_optional_collection` error here? Those files were not touched and seemed to have passed before?

Not sure why they pop up now. But feel free to add some `//swiftlint:disable:this discouraged_optional_collection` to the lines.

2023-10-31 04:55 UTC, Supereg approved these changes
Thank you 🚀

2023-10-31 05:03 UTC, vishnuravi commented
> > @Supereg any idea why we are getting the `discouraged_optional_collection` error here? Those files were not touched and seemed to have passed before?
> 
> Not sure why they pop up now. But feel free to add some `//swiftlint:disable:this discouraged_optional_collection` to the lines.

Thanks. I added this and then I got a line length - sometimes you just can't win!!

2023-10-31 05:21 UTC, Supereg commented
> > > @Supereg any idea why we are getting the `discouraged_optional_collection` error here? Those files were not touched and seemed to have passed before?
> > 
> > 
> > Not sure why they pop up now. But feel free to add some `//swiftlint:disable:this discouraged_optional_collection` to the lines.
> 
> Thanks. I added this and then I got a line length - sometimes you just can't win!!

There is also a `swiftlint:disable:previous ...` which might be helpful here 😅

2023-10-31 05:28 UTC, vishnuravi commented
> > > > @Supereg any idea why we are getting the `discouraged_optional_collection` error here? Those files were not touched and seemed to have passed before?
> > > 
> > > 
> > > Not sure why they pop up now. But feel free to add some `//swiftlint:disable:this discouraged_optional_collection` to the lines.
> > 
> > 
> > Thanks. I added this and then I got a line length - sometimes you just can't win!!
> 
> There is also a `swiftlint:disable:previous ...` which might be helpful here 😅

Fixed the SwiftLint error and got a REUSE error. Tonight is just not my night Andreas. 😅

2023-10-31 05:58 UTC, PSchmiedmayer commented
@vishnuravi @Supereg Thank you for this fix!

Can we use this PR to directly resolve #22 which would have also been helpful to be done right in #32 to ensure that we don't run into the same issues again?
String catalogues should flag these issues and should automate these processes in the future 👍

2023-10-31 05:58 UTC, PSchmiedmayer requested changes
@vishnuravi @Supereg Thank you for this fix!

Can we use this PR to directly resolve #22 which would have also been helpful to be done right in #32 to ensure that we don't run into the same issues again?
String catalogues should flag these issues and should automate these processes in the future 👍

2023-10-31 20:29 UTC, Supereg approved these changes
Thanks for the great work 🚀 

As we migrated to String catalogues, we have some strings being picked up from the mock or preview implementations. I annotated every localization key I could find.
Would be great if you could review the usages of those keys and check if it makes sense to use the `Text(verbatim:)` initializer instead, or, otherwise, add a translation for those strings.

Otherwise, the PR looks great, thanks for the effort 🎉

2023-10-31 20:29 UTC, Supereg commented on Sources/SpeziAccount/Resources/Localizable.xcstrings
> +    },
Can we check where this two translations are coming from?
Seems like there are some `Text` views that do not use the [Text(verbatim:)](https://developer.apple.com/documentation/swiftui/text/init(verbatim:)) initializer.

2023-10-31 20:29 UTC, Supereg commented on Sources/SpeziAccount/Resources/Localizable.xcstrings
> +    },
Seems like there are also missing translations or misused Text initializers?

2023-10-31 20:29 UTC, Supereg commented on Sources/SpeziAccount/Resources/Localizable.xcstrings
> +    },
If these are used within the Previews, we might just rewrite the previews to use the `Text(verbatim:)` initializer?

2023-10-31 20:29 UTC, Supereg commented on Sources/SpeziAccount/Resources/Localizable.xcstrings
> +    },
Yep, seems like I forgot to use the `Text(verbatim:)` initializer all the Mock implementations.

2023-10-31 20:29 UTC, Supereg commented on Sources/SpeziAccount/Resources/Localizable.xcstrings
> +    },
here as well

2023-10-31 20:29 UTC, Supereg commented on Sources/SpeziAccount/Resources/Localizable.xcstrings
> +    },
Seems like either missing translation or again missing use of the `Text(verbatim:)` initializer

2023-10-31 20:29 UTC, Supereg commented on Sources/SpeziAccount/Resources/Localizable.xcstrings
> +    },
Probably a string coming from the previews?

2023-10-31 21:50 UTC, PSchmiedmayer approved these changes
Thank you @vishnuravi! Happy to get the PR merged once @Supereg is happy and his comments are resolved 🚀

2023-10-31 21:51 UTC, PSchmiedmayer commented on Package.swift
Would be great if we can also just include the MD link check in there as well, just so we get it into the different repos as we make different smaller or bigger PRs 👍

2023-10-31 21:56 UTC, vishnuravi commented
> Thank you @vishnuravi! Happy to get the PR merged once @Supereg is happy and his comments are resolved 🚀

@Supereg and I are having a side chat on Slack, we are not sure it is possible to designate strings like "Mock Simple AccountService" below as non-localized:

```
let configuration = AccountServiceConfiguration(name: "Mock Simple AccountService", supportedKeys: .arbitrary)
```

Any thoughts there?

2023-11-01 08:04 UTC, PSchmiedmayer commented
@vishnuravi Following up on our discussion today: I addressed most of the issues with the localization files and only needed to translate a few very limited elements and added comments for the rest.

Looking forward to getting the PR finished and feel free to merge it once all the conversations are resolved 👍

2023-11-06 20:04 UTC, Supereg commented
fyi, I'm currently rebasing this PR and taking care of it getting it merged if that is alright for you @vishnuravi 👍

2023-11-06 20:54 UTC, vishnuravi commented
> fyi, I'm currently rebasing this PR and taking care of it getting it merged if that is alright for you @vishnuravi 👍 

That sounds great, thank you @Supereg!

2023-11-07 00:11 UTC, PSchmiedmayer approved these changes
Thank you for finishing the PR @Supereg and thanks for all the work here @vishnuravi!

2023-11-07 00:11 UTC, merged