Show a message when no account services are set up
StanfordSpezi/SpeziAccount pull request #6
Opened 2023-06-08 15:12 UTC by Supereg

# Show a message when no account services are set up

## :recycle: Current situation & Problem
Currently, when there are no `AccountService`s set up the `AcountServicesView` just displays nothing instead of the button. Especially for developers new to the framework ecosystem, they might be unfamiliar that AccountServices are set up globally and that the respective Signup/Login buttons are place automatically.

## :bulb: Proposed solution
This PR tries to avoid this problem by giving a visual hint on why no `AccountServiceButton`s are shown. 

## :gear: Release Notes 
* Improved diagnostics when no `AccountService`s are set up.

## :heavy_plus_sign: Additional Information

@PSchmiedmayer We might consider an alternative where we don't display the diagnostic message but only print the message to the app logger. Are there any guidelines on how to deal with (configuration) issues like these in the Spezi framework ecosystem?

Additionally, the PR fixes some missing translations and misspelled translations in previews.

### Related PRs
--

### Testing
This case is currently not covered in the UI tests.

### Reviewer Nudging
All the primary changes happen in the `AccountServicesView`.

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### Attachments 

<img width="497" alt="Bildschirmfoto 2023-06-08 um 17 05 30" src="https://github.com/StanfordSpezi/SpeziAccount/assets/9783857/7967051c-6073-4373-9907-c6538051086b">

2023-06-08 17:29 UTC, PSchmiedmayer requested changes
Thank you for the addition, great addition and helps new users of Spezi Account! 🚀

It would be great if you can add an additional UI test that can verify that behavior in your UI tests to ensure that a user can see the message.
My suggestion: 
- We could define if account services should be added or not using a feature flag (like to do this in the template app) and then either add or not add some account services.
- We can then pass this feature flag in the UI test (like we do it in the template app) and then investigate if the warning message appears.

What do you think?

2023-06-08 17:29 UTC, PSchmiedmayer commented on Sources/SpeziAccount/Resources/de.lproj/Localizable.strings
> +"SIGN_UP" = "Benutzerkonto Erstellen";
Nice, thank you!

2023-06-08 17:29 UTC, PSchmiedmayer commented on Sources/SpeziAccount/Resources/en.lproj/Localizable.strings
> +"MISSING_ACCOUNT_SERVICES" = "No Account Services where set up.\n Please refer to the documentation of the SpeziAccount package on how to set up an AccountService!";
We would need a German representation of this localization string as well.

2023-06-08 17:31 UTC, PSchmiedmayer commented
@Supereg Regarding your usability question: I like the visual message in the UI. We could even add a link to the documentation there, that could be doable. I think that the error is more a runtime error and less a user error but this location is a good way for developers to easily spot any mistake and point them to the right location, I like this approach over a command line log.

2023-06-09 13:35 UTC, Supereg commented
> Thank you for the addition, great addition and helps new users of Spezi Account! 🚀
> 
> It would be great if you can add an additional UI test that can verify that behavior in your UI tests to ensure that a user can see the message. My suggestion:
> 
> * We could define if account services should be added or not using a feature flag (like to do this in the template app) and then either add or not add some account services.
> * We can then pass this feature flag in the UI test (like we do it in the template app) and then investigate if the warning message appears.
> 
> What do you think?

Sounds good. Implemented exactly that. Thanks for the hints on how to approach this 👍

2023-06-09 13:37 UTC, bauer-andreas commented
> @Supereg Regarding your usability question: I like the visual message in the UI. We could even add a link to the documentation there, that could be doable. I think that the error is more a runtime error and less a user error but this location is a good way for developers to easily spot any mistake and point them to the right location, I like this approach over a command line log.

Yes that is basically where my original motivation was coming from when I tried to understand the architecture of the app but couldn't locate the AccountServices buttons in the SwiftUI Previews. I added a button to the UI that opens the respective SpeziAccount documentation page.

2023-06-09 14:54 UTC, Supereg commented
Okay, I tried to debug this for 2 hours now. With the changes made in this PR the App freezes when clicking any of the AccountServiceButtons (e.g. open UITest app -> click "Login" -> click "Username and Password" -> freeze). At this point the app will continuously eat memory.
When switching to the main branch this doesn't happen.

2023-06-09 15:56 UTC, Supereg commented
Any ideas why the code coverage still fails with 0%? Seems off by a lot 😬

2023-06-13 20:22 UTC, PSchmiedmayer approved these changes
Thank you @supereg , a great addition to the module!

I only had a few smaller comments that should be easy to address. The fact that we do get any code coverage information is strange, we should investigate that in more detail; I will take a look at that.

2023-06-14 01:18 UTC, PSchmiedmayer commented
@Supereg I did resolve the code coverage issue using some additional flags. The tool now correctly reports the code coverage report.
Unfortunately we have the issue that the `if #DEBUG` statement seems to be ignored in the Swift Package which results in changes in the preview being reported in the code coverage. I was not able to find a good workaround for that and will track that issue in a separate issue in the main Swift Package Template repo.

2023-06-17 14:04 UTC, Supereg commented on Sources/SpeziAccount/AccountServicesView.swift
> +                            let docsUrl = URL(string: "https://swiftpackageindex.com/stanfordspezi/speziaccount/documentation/speziaccount/createanaccountservice")!
Control flow can't be added to SwiftUI result builders. I moved out the URL construction into a computed property.

2023-06-19 04:49 UTC, PSchmiedmayer commented
@Supereg The one test seems to fail due to an issue with our GitHub runner, I will check this in the office tomorrow morning: https://github.com/StanfordSpezi/SpeziAccount/actions/runs/5298702381/jobs/9601398047?pr=6

The UI test seems to fail due to an iOS 17 problem on the runners: https://github.com/StanfordSpezi/SpeziAccount/actions/runs/5298702381/jobs/9601398175?pr=6

Tracked the issue in this GitHub issue: https://github.com/StanfordBDHG/XCTestExtensions/issues/11

This PR should address the issue, will merge it once I have full iOS 17 compatibility ready: https://github.com/StanfordBDHG/XCTestExtensions/pull/12

2023-06-22 16:15 UTC, Supereg commented
I double checked, and the CI uses the updated version of XCTestExtensions. UI Tests are passing locally. 
UI Tests are failing in the CI with this error getting spammed into the logs:

`
2023-06-22 08:55:11.779 xcodebuild[13749:200357] [MT] IDEFileReferenceDebug: [Load] <IDEFileReference, 0x600007a1fe00: name:SpeziAccount.docc path:absolute:/Users/githubrunner/actions-runner/_work/SpeziAccount/SpeziAccount/Sources/SpeziAccount/SpeziAccount.docc> Failed to load container at path: /Users/githubrunner/actions-runner/_work/SpeziAccount/SpeziAccount/Sources/SpeziAccount/SpeziAccount.docc, Error: Error Domain=com.apple.dt.IDEContainerErrorDomain Code=6 "Cannot open "SpeziAccount.docc" as a "Folder" because it is already open as a "Swift User Managed Package Folder"." UserInfo={NSLocalizedDescription=Cannot open "SpeziAccount.docc" as a "Folder" because it is already open as a "Swift User Managed Package Folder".}
`

Just to track it here as well.

2023-06-23 21:22 UTC, merged